### Variables
@baseUrl = http://localhost:3000
@token = Q90Iy0ia3o030ch0pMLjgZjJozXwgfeK
@productId = cmqj9jizf0000a4pko1e0lw3o

### Lister les produits (public, sans auth)
GET {{baseUrl}}/api/products

###

### Créer un produit sans auth → doit retourner 401
POST {{baseUrl}}/api/products
Content-Type: application/json

{
  "name": "T-Shirt Basic",
  "price": 29.99,
  "stock": 100
}

###

### Créer un produit avec auth
POST {{baseUrl}}/api/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "T-Shirt Basic",
  "description": "100% coton bio",
  "price": 29.99,
  "stock": 100
}

###

### Détail d'un produit
GET {{baseUrl}}/api/products/{{productId}}

###

### Modifier le stock
PATCH {{baseUrl}}/api/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "stock": 75
}

###

### Supprimer un produit
DELETE {{baseUrl}}/api/products/{{productId}}
Authorization: Bearer {{token}}


### Recherche avec pagination
GET {{baseUrl}}/api/products?search=shirt&page=1&limit=5&minPrice=10&maxPrice=50